Company showcase component
ReCoded-Org/-capstone-IQLBPS-jobie pull request #68
Opened 2022-10-26 17:07 UTC by marwazpov

this branch is related to issue #14

2022-10-28 05:29 UTC, marwazpov commented
Hi @AllanSaleh , did anyone push into this by mistake?

2022-10-28 16:12 UTC, AllanSaleh commented
Hi, @marwazpov Yes, I updated this branch to fix the test from failing and it worked. I will see why it failed again.

2022-10-31 03:50 UTC, AllanSaleh commented
Hey @marwazpov Yes, I think someone pushed onto your branch. I will undo those changes.

2022-11-01 00:48 UTC, AllanSaleh requested changes
Great job on creating this component!!🙌

Just a couple of small changes to the design are required:
-  The paragraph has no space on the left and is sticking to the edge of the screen. I think adding some space to it will make it look better.
![image](https://user-images.githubusercontent.com/32653855/199134758-b3d43a2a-acfb-44d3-8df6-05917ca71d95.png)
- The paragraph is aligned to the left still on mobile screens. If you can align it to the center on the mobile screen may make it look better.
- Maybe add some padding to the top and bottom of the component to give it some space from other components.
![image](https://user-images.githubusercontent.com/32653855/199135155-8eaa4440-08ca-4f1e-9324-6e466e91930f.png)

Other than these small tweaks, your component is coded great!👏

2022-11-01 21:52 UTC, marwazpov commented
Hi @AllanSaleh , I have done the requested changes! I have also tried to make the component more reusable so I can use it in issue number 21. Let me know what you think ☺️

2022-11-03 17:57 UTC, AllanSaleh approved these changes
Superb work!!😍
Your component is now perfect!!🎊
Keep up the great work!!🔥

2022-11-03 17:57 UTC, AllanSaleh commented on src/data/showCaseData.js
> +}
Great work on separating the data from the component and putting it into its own file!

2022-11-03 17:57 UTC, AllanSaleh commented on src/components/companyShowcaseComponent/CompanyShowcaseComponent.jsx
> +}
AWESOME work on using props to make the component reusable! It is really well-coded!! This component can be used for different data now!! All thanks to you!🙌
And well done on using slice!!!👏

2022-11-03 18:04 UTC, merged